name: Test DQC
on:
  push: # ci work when pushing master branch
    branches:
      - master
  pull_request: # ci work when creating a PR to master branch
    branches:
      - master
jobs:
  test-dqc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create env.yml
      shell: bash
      run: |
        python -m pip install --upgrade pip;
        pip install conda-merge; 
        conda-merge requirements/env_dqc.yml requirements/env_test.yml > env.yml
    - name: Install all dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: dqc
        channels: conda-forge,defaults
        python-version: ${{ matrix.python-version }}
        environment-file: env.yml
    - name: Conda info
      shell: bash -el {0}
      run: conda info
    - name: Install DeepChem
      shell: bash -l {0}
      run: pip install -e .
    - name: Show packages
      shell: bash -l {0}
      run: pip freeze
    - name: Import numpy
      shell: bash -l {0}
      run: python -c 'import numpy as np; print ("numpy version is %s" % np.__version__)'
    - name: Test Install
      shell: bash -l {0}
      run: |
        python -c 'import deepchem; print("DeepChem version %s" % deepchem.__version__)'
        python -c 'import torch; print("Torch version %s" % torch.__version__)'
        python -c 'import dqc; print("DQC version %s" % dqc.__version__)'
        python -c 'import xitorch; print("Xitorch version %s" % xitorch.__version__)'
        python -c 'import pylibxc; print("pylibxc version %s" % pylibxc.version.__version__)'
    - name: PyTest
      shell: bash -l {0}
      run: |
        echo "running dqc pytest"
        pytest -v -m 'dqc' deepchem
